# fly.toml app configuration file generated for mimir-bot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mimir-bot'
primary_region = 'fra'

[build]

[env]
  GEMINI_MODEL = 'gemini-3.5-flash'
  NODE_ENV = 'production'
  TTS_VOICE = 'fr-FR-HenriNeural'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
