services:
  - type: web
    name: mimir-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: GROQ_API_KEY
        sync: false
      - key: TTS_VOICE
        value: fr-FR-HenriNeural
